### ISSUE TITLE
Open Discussion

### ISSUE THREAD

**Issue by adamk33n3r** [Bullish53/TTS#1]
Hey, just wanted to reach out and see what your thoughts were about both of our plugins living on (I tried messaging you on discord but it errored). I don't want to step on your toes, and seeing as our plugins goals are different (interface narration), I can see them living together in harmony. Might just need some established boundaries. Now knowing that tts-over-network isn't very time-expensive, I'm curious in trying it as an option for mine. But I don't want to take what is unique about yours and make it obsolete, especially seeing the amount of effort you put into it.

I'd also be willing to have a conversation about merging our projects if you think that'd be beneficial over trying to keep them distinct and separate.

Anyway, cool plugin idea! I'm impressed with the features. And welcome to runelite plugin development!

**Comment by Bullish53** [comment]
Hi, its fine and its good that people can choose from multiple options with different features. Merging them could be possible too if you have any ideas on how we could do that.
