### ISSUE TITLE
semi-frequent NegativeArraySizeException

### ISSUE THREAD

**Issue by Patricol** [Bullish53/TTS#13]
I see nothing else relevant but
```
java.lang.NegativeArraySizeException: -1
	at com.ttsplugin.main.TTSPlugin.play(TTSPlugin.java:264)
	at com.ttsplugin.main.TTSPlugin.lambda$startUp$2(TTSPlugin.java:102)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
in the log output when running `runelite --debug`.

Whenever this happens, a line fails to be read. It's never an interruption-midway; the lines just don't start. Chatting with the same NPCs over the same lines shows it doesn't always happen for the same lines; but from playing with another person also using this plugin, we tend to have this problem on the same lines of dialog.

**Comment by Patricol** [comment]
Happens on both Windows and Linux. Occurs even with all other plugins (including default ones) disabled.

**Comment by Bullish53** [comment]
Seems to be an error serverside so it doesn't send the audio. Ill look into it if it still keeps happening

**Comment by Bullish53** [comment]
This happened because the server denied the request due to the audio being too large which could happen if your voice rate is very low or the message very big. I increased the limit serverside now so this should be fixed.
